### ISSUE TITLE
Supporting AWS proxy protocol

### ISSUE THREAD

**Issue by shaneutt** [datawire/ambassador-chart#150]
It would appear that in order to support proxy protocol v2 integrated with AWS using Ambassador one would need to create a `Module` configuration which will enable it in the Ambassador control plane:

```yaml
apiVersion: getambassador.io/v2
kind:  Module
metadata:
  name: ambassador
  namespace: ambassador
spec:
  config:
    use_proxy_proto: true
```

And decorate the service with relevant annotations, this for classic ELB:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: kubeaddons
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
```

Or this for NLB:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: kubeaddons
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
```

This all according to my review of your documentation:

* https://www.getambassador.io/docs/latest/topics/running/ambassador/#allow-proxy-protocol-use_proxy_proto
* https://www.getambassador.io/docs/pre-release/topics/running/ambassador-with-aws/#ambassador-edge-stack-on-aws

There may be more to it than that (I'll need to continue to review the documentation) but the purpose of this issue is **specific to the helm chart**:

I haven't seen any reference to the use of `proxy_proto` throughout the chart except for a single reference to a configuration override, and I don't see a higher level configuration available to enable proxy protocol on specific cloud providers.

The purpose of this issue is to request a high level configuration option for the chart to deploy a `proxy_protocol` ready and enabled service configuration, preferably something like this:

```shell
$ helm install --create-namespace --namespace ambassador --set proxyProtocol.enabled=true ambassador ambassador
```

As an MVP at least having this option available for AWS based loadbalancers would be appreciated.

Thank you!
