### ISSUE TITLE
Missing Network Policies Support 

### ISSUE THREAD

**Issue by djsly** [datawire/ambassador-chart#22]
It would be good to allow  the creation of network policies as part of the chart to cover as a minimum the ingress of the exposed port. 

We can work on the PR if this is an accepted feature.

**Comment by bergerx** [comment]
Any progress here, we have some network policies in all namespaces, and seems like without defining an allow all ingress rule ambassador doesnt work. I'd expect it to be blocked in egress bit not ingress rules.

Ambassador reaches out to the pods, it's not supposed to be reached out by others as i understood, but when we define any ingress ambassador stops working until i define something like this (i didn't yet check if a specific ip would be enough):

```
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: allow-ingress-from-all-ips
spec:
  podSelector: {}
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
```
