### ISSUE TITLE
Service annotations do not create CRD related resources

### ISSUE THREAD

**Issue by Aeysol** [datawire/ambassador-chart#27]
When using the `service.annotations` section all resources defined inside the `getambassador.io/config` key are not created at all.

For example:
```yaml
service:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: getambassador.io/v2
      kind: Host
      metadata:
        name: minimal-host
      spec:
        hostname: host.example.com
        acmeProvider:
          authority: none
        requestPolicy:
          insecure:
            action: Route
```
does not create any resources.

```
> kubectl -n ambassador get host minimal-host -o yaml
No resources found in ambassador namespace.
```
