### ISSUE TITLE
Cannot use ClusterIP type Service

### ISSUE THREAD

**Issue by mnikolic-ep** [datawire/ambassador-chart#50]
### Description

I am installing the Ambassador API Gateway using Helm 3 and Terraform. I'm also trying to follow [this blog post (on Medium)](https://medium.com/@cfatechblog/shaping-chick-fil-a-one-traffic-in-a-multi-region-active-active-architecture-6fb982597d45) to use an AWS ALB as the ingress to my cluster and Ambassador.

The default installation where you update just the values `image.repository`, `image.tag` and `enableAES` works fine. (Based on [these docs](https://www.getambassador.io/docs/latest/topics/install/install-ambassador-oss/#2-install-ambassador-api-gateway))

However, when I try to change the service type to `ClusterIP` I get a Helm validation error.

When I try to fix the validation error by adding a `targetPort` (which is included in the `LoadBalancer` type Service), I get an error from K8s when trying to update the Service.

#### ClusterIP Service Config in values.yaml

```yaml
service:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      # targetPort: 8080
  selector:
    service: ambassador
  externalTrafficPolicy:
  annotations:
```

#### Errors

```
error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].ports[0]): missing required field "containerPort" in io.k8s.api.core.v1.ContainerPort
```

```
cannot patch "ambassador" with kind Service: Service "ambassador" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
```

**Comment by jjLudin** [comment]
Hi Mila, I also faced the same issue. The following steps worked for me. 

1. ClusterIP Service Config in values.yaml
```yaml
service:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443

  externalTrafficPolicy:
  annotations:
```

2. Port-forward to 8443
```bash
kubectl port-forward -n ambassador deployment/ambassador 8443:8443
```

You should be able to navigate to `https://localhost:8443`. I hope this helps!
