### ISSUE TITLE
Different behavior on SSO keycloak integration when installing AES with helm chart and edgectl

### ISSUE THREAD

**Issue by joseguerrero** [datawire/ambassador-chart#51]
Hello, I have deployed AES on my K8S cluster to test SSO login with keycloak.

My cloud provider is AWS.

I'm using the latest official helm chart (datawire/ambassador) with the following values: 

```
daemonSet: true

service:
  type: LoadBalancer

  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
              
  externalTrafficPolicy: Local
  loadBalancerSourceRanges:
  - <some ip address>
  - <some ip address>
  - <some ip address>

crds:
  enabled: true
  create: true
  keep: true

licenseKey:
  value: "<some comunity license>"

authService:
  create: true
```

And these are my crds: 

```
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: aes
  namespace: ambassador
spec:
  hostname: aes.example.in
  acmeProvider:
    authority: none
  tlsSecret:
    name: aes.example-secret
  requestPolicy:
    insecure:
      action: Route
      additionalPort: 8080

---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  httpbin
  namespace: ambassador
spec:
  prefix: /httpbin/
  service: http://httpbin.org
  host: aes.example.in

---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: keycloak
  namespace: ambassador
spec:
  prefix: /auth
  rewrite: ""
  service: keycloak.github
  host: aes.example.in

---
apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: keycloak
  namespace: ambassador
spec:
  OAuth2:
    authorizationURL: https://aes.example.in/auth/realms/demo
    clientURL: https://aes.example.in
    audience: app
    clientID: app
    secret: 8517c278-0ae8-40e5-b418-20199b7e3fb5
    insecureTLS: true

---
apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: httpbin-policy
  namespace: ambassador
spec:
  rules:
    - host: "*"
      path: /httpbin/*
      public: false
      filters:
        - name: keycloak
```

I have configured an Oauth application in github, setup keycloak on my cluster, mainly following the instructions on this repository: https://github.com/datawire/pro-ref-arch/tree/master/api-auth-with-github

So when it comes to test the SSO, in the browser I head to https://aes.example.in/httpbin/ and what I get is a 504 (I know that's the status code I get when check on the ambassador container logs for the path `/httpbin/`).

On the other hand if I install AES with edgectl and using exactly the same crds mentioned above, the SSO works as expected; I go to https://aes.example.in/httpbin/ and then I get redirected to my keycloak login page, I select to authenticate with github, enter credentials and finally get to see https://aes.example.in/httpbin/ correctly.

Am I missing something when it comes to the helm chart installation?

Just to be clear, I made a clean installation of AES both when installing with helm chart and `edgectl`, so the steps are reproducible, and more than 8 times I had the same result, SSO only works when I install AES with `edgectl`.

Thanks!
