### ISSUE TITLE
Support Datadog statsd sink DaemonSet

### ISSUE THREAD

**Issue by ellisvalentiner** [datawire/ambassador-chart#82]
By default, the DataDog chart adds the Datadog Agent to all nodes in the cluster via a DaemonSet. If DataDog StatsD Sink is deployed as a daemon set, AES can't resolve the host IP (i.e. `STATSD_HOST=localhost`).

Example logs:

```
2020-06-02 18:25:48 diagd 1.5.0 [P96TAEW] ERROR: Unable to resolve statsd-sink to IP : [Errno -2] Name does not resolve
2020-06-02 18:25:48 diagd 1.5.0 [P96TAEW] ERROR: Stats will not be exported to statsd-sink
```

Changing the Deployment [`STATSD_HOST` environment variable](https://github.com/datawire/ambassador-chart/blob/master/templates/deployment.yaml#L175) to use `valueFrom` resolves the issue.

```yaml
- name: STATSD_HOST
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: status.hostIP
```

It would be nice if the AES Helm chart could support Datadog Agent deployed as a Daemon Set.
